
CFLAG := -I/usr/local/cuda/include
LFLAG := -L/usr/local/cuda/lib64

all:gemm

gemm:gemm1.o
	g++ $^ -o $@ $(LFLAG) -lOpenCL

%.o:%.cpp
	g++ -c $^ -o $@ $(CFLAG) $(LFLAG) -lOpenCL -DonX86

clean:
	rm -rf *.o *.aocx *.aoco gemm1 gemm
