TGT:=clx_cuda

CFLAG := -I/usr/local/cuda/include -Wwrite-strings
LFLAG := -L/usr/local/cuda/lib64

all:environment $(TGT)

$(TGT):clx.o
	g++ -g $^ -o $@ $(LFLAG) -lOpenCL -Ofast

%.o:%.cpp
	g++ -g -c $^ -o $@ $(CFLAG) $(LFLAG) -lOpenCL -DonX86 -Ofast

clean:
	rm -rf *.o $(TGT)

environment:
	@echo CFLAG $(CFLAG)
	@echo LFLAG $(LFLAG)
