TGT:=clx_cuda

CFLAG := -I/usr/local/cuda/include -Wwrite-strings
LFLAG := -L/usr/local/cuda/lib64 -Wwrite-strings

all:environment $(TGT)

$(TGT):clx.o
	g++ -g $^ -o $@ $(LFLAG) -lOpenCL

%.o:%.cpp
	g++ -g -c $^ -o $@ $(CFLAG) $(LFLAG) -lOpenCL -DonX86

clean:
	rm -rf *.o $(TGT)

environment:
	@echo CFLAG $(CFLAG)
	@echo LFLAG $(LFLAG)
