TGT:=clx_cuda

CFLAG := -I/usr/local/cuda/include
LFLAG := -L/usr/local/cuda/lib64

all:environment $(TGT)

$(TGT):gemm1.o
	g++ -g $^ -o $@ $(LFLAG) -lOpenCL

%.o:%.cpp
	g++ -g -c $^ -o $@ $(CFLAG) $(LFLAG) -lOpenCL -DonX86

clean:
	rm -rf *.o $(TGT)

environment:
	@echo CFLAG $(CFLAG)
	@echo LFLAG $(LFLAG)
